export const locations = {
  schoolChapters: [
    { name: "Southwest High School Chapter", location: "Minneapolis, Minnesota" },
    { name: "Washburn High School Chapter", location: "Minneapolis, Minnesota" },
    { name: "Saint Paul Academy Chapter", location: "Minneapolis, Minnesota" },
    { name: "Mansfield High School Chapter", location: "Mansfield, Texas" },
    { name: "Obra D. Tompkins High School Chapter", location: "Katy, Texas" },
    { name: "Central Pennsylvania Chapter", location: "Pennsylvania" },
    { name: "Emerson High School Chapter", location: "McKinney, Texas" },
    { name: "Harvest Collegiate High School Chapter", location: "New York, New York" },
    { name: "Mark T. Sheehan High School Chapter", location: "Wallingford, Connecticut" },
    { name: "Irvington High School Chapter", location: "Fremont, California" },
    { name: "Simav Science High School Chapter", location: "Turkiye" },
    { name: "Bedford High School Chapter", location: "Bedford, Massachusetts" },
    { name: "Chantilly High School Chapter", location: "Chantilly, Virginia" },
    { name: "Apex High School Chapter", location: "Apex, North Carolina" },
    { name: "Forsyth Central High School Chapter", location: "Cumming, Georgia" },
    { name: "Heritage High School", location: "Frisco, Texas" },
    { name: "Wilsonville High School Chapter", location: "Wilsonville, Oregon" },
    { name: "McLean High School Chapter", location: "McLean, Virginia" },
    { name: "South County High School", location: "Lorton, Virginia" },
    { name: "Otay Ranch High School Chapter", location: "Chula Vista, California" },
    { name: "Dougherty Valley High School Chapter", location: "San Ramon, California" },
    { name: "New Canaan High School Chapter", location: "New Canaan, Connecticut" },
    { name: "West Forsyth High School Chapter", location: "Clemmons, North Carolina" },
    { name: "Gems Founders School Dubai Chapter", location: "United Arabs Emirates" },
    { name: "Brooklyn Technical High School Chapter", location: "Brooklyn, New York" },
    { name: "Al Manar International School", location: "Doha, Qatar" },
    { name: "Montgomery High School Chapter", location: "Montgomery Township, New Jersey" },
    { name: "El Toro High School Chapter", location: "Lake Forest, California" },
    { name: "Somerset County Vocational & Technical High School", location: "Bridgewater Township, New Jersey" },
    { name: "Mt. Hebron High School Chapter", location: "Ellicott City, Maryland" },
    { name: "Cumberland Valley High School Chapter", location: "Cumberland County, Pennsylvania" },
    { name: "Dy Patil International School Nerul", location: "Mumbai, India" },
  ],
  regionalChapters: [
    { name: "Irvine Chapter", location: "California" },
    { name: "California State Chapter", location: "California" },
    { name: "Jamshedpur Chapter", location: "Jamshedpur, India" },
    { name: "Istanbul Chapter", location: "Istanbul, Turkiye" },
    { name: "Karachi Chapter", location: "Sindh, Pakistan" },
    { name: "Ethiopia Chapter", location: "Ethiopia" },
    { name: "Nepal Chapter", location: "Nepal" },
    { name: "Noida Chapter", location: "Noida, India" },
    { name: "South Pasadena Chapter", location: "South Pasadena, California" },
    { name: "Hyderabad Chapter", location: "Hyderabad, Pakistan" },
    { name: "Dubai Chapter", location: "Dubai, United Arab Emirates" },
    { name: "Greenville Chapter", location: "Greenville, North Carolina" },
    { name: "Australia Chapter", location: "Australia" },
    { name: "Morocco Chapter", location: "Morocco" },
    { name: "New Delhi Chapter", location: "India" },
    { name: "Crystal Coast Chapter", location: "Crystal Coast, North Carolina" },
    { name: "Vietnam Chapter", location: "Vietnam" },
    { name: "Bangalore Chapter", location: "India" },
    { name: "New York City Chapter", location: "New York" },
    { name: "Hyderabad Chapter", location: "India" },
    { name: "Tampa Chapter", location: "Florida" },
    { name: "St. Louis Chapter", location: "Missouri" },
  ],
};